### ISSUE TITLE
Support for intllib

### ISSUE THREAD

**Issue by BrunoMine** [ciubotaru/compost#1]
I intend to use this mod in [my project](https://github.com/BrunoMine/sociedades), but for this it needs to allow translations ([intllib](https://forum.minetest.net/viewtopic.php?id=4929)) Is it possible that this will be done soon? Otherwise I can do this and create a pull request.

**Comment by ciubotaru** [comment]
Actually, I added intllib support long ago. Currently it is in [unstable](https://github.com/ciubotaru/compost/tree/unstable) branch only, because I did not test it. As a first step, it would be great if you could test it and confirm that it works. Then I will merge it into stable branch.

I looked at your project. Apparently the main language there is Portuguese. If you can create a Portuguese translation for this mod, I will happily add it. Pull requests always welcome :-)

Edited: First I mistook Portuguese for Spanish. My apologies.

**Comment by BrunoMine** [comment]
Translations are working fine, but I'd like to say a few things.

Intllib has been improved to support translation with gettext translation tools. Current translations are very simple, so this should not make much difference.

The translations below are redundant.
`progress: 0%`
`progress: @1%`
If the variable `@1` assumes the value `0`, it can be used in place of the first translation.
`S("prograss @1%", "0")`
`S("prograss @1%", percent)`

[Add portuguese translation](https://github.com/ciubotaru/compost/pull/2)

**Comment by ciubotaru** [comment]
- Thank you very much for testing intllib functionality.
- Your pull request (Portuguese translation) has been merged.
- The redundant translation string has been removed.
- Version [0.0.2](https://github.com/ciubotaru/compost/releases/tag/v0.0.2) released.
- Transition to gettext is left for a later date.
